DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

// WRITE THE CREATE SCRIPTS FOR ALL THREE TABLES
CREATE TABLE DEPARTMENT(
    id INT NOT NULL AUTO_INCREMENT
);



